map: "warehouse"
world: "warehouse"
rviz_file: "sim_env.rviz"

robots_config:
  - robot1_type: "turtlebot3_waffle"
    robot1_location_method: "amcl"
    robot1_global_planner: "gradient"
    robot1_local_planner: "rpp"
    robot1_optimizer: ""
    robot1_x_pos: "0.0"
    robot1_y_pos: "0.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "0.0"

# * global planner
#   * graph_planner
#     * astar
#     * jps
#     * bi_jps
#     * gbfs
#     * dijkstra
#     * dstar
#     * lpa_star
#     * dstar_lite
#     * theta_star
#     * lazy_theta_star
#     * s_theta_star
#     * hybrid_astar
#     * gradient
#
#   * roadmap_planner
#     * voronoi
#     * visibility
#     * quartree
# 
#   * sample_planner
#     * rrt
#     * rrt_star
#     * informed_rrt
#     * rrt_connect
#     * quick_informed_rrt
#
#   * evolutionary_planner
#     * aco
#     * pso
#     * ga
#
# * local planner
#   * dwa
#   * pid
#   * apf
#   * rpp
#   * lqr
#   * static
#
# * optimizer
#   * minimumsnap_optimizer
#   * constrained_optimizer
#   * conjugate_optimizer
#   * lbfgs_optimizer

plugins:
  # pedestrians: "pedestrian_config.yaml"
  # obstacles: "obstacles_config.yaml"
  map_layers: "map_layers_config.yaml"
